import { Noto_Sans } from "next/font/google";
import "./globals.css";

const font = Noto_Sans({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={font.className}>
				<div className="top-bar">
					<h2>POMO</h2>
				</div>
				<div className="app">{children}</div>
			</body>
		</html>
	);
}
